#!/bin/sh

set -e

case $RUNEBASE_NETWORK in
  local|regtest)
    SELECT_NETWORK=-regtest
    ;;
  test|testnet)
    SELECT_NETWORK=-testnet
    ;;
  main|mainnet)
    SELECT_NETWORK=
    ;;
  *)
    echo "Unknown network: $RUNEBASE_NETWORK"
    exit 1
esac

mkdir -p $RUNEBASE_DATADIR

exec runebased ${SELECT_NETWORK} \
  -rpcbind=0.0.0.0:3889 -rpcallowip=172.17.0.0/16 \
  -datadir=$RUNEBASE_DATADIR \
  -logevents \
  -rpcuser=$RUNEBASE_RPC_USER -rpcpassword=$RUNEBASE_RPC_PASS \
  -printtoconsole
