version: '3'

services:
  insightapi:
    build: .
    links:
    - mongo
    volumes:
    - ./:/data
    ports:
    - "3001:3001"
    - "18332:18332"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
